worldevents/eventslist/urls.py
from django.conf.urls import patterns, include, url
from eventslist import views

urlpatterns = patterns('',
    url(r'^deleteevent/(\w+)$', views.deleteevent, name='deleteevent'),
    url(r'^deleteevent$', views.deleteevent, name='deleteevent'),
    url(r'^editevent/(\w+)$', views.editevent, name='editevent'),
    url(r'^editevent$', views.editevent, name='editevent'),
    url(r'^searchevents/(\d+)/$', views.searchevents, name='searchevents'),
    url(r'^searchevents/(\d+)$', views.searchevents, name='searchevents'),
    url(r'^searchevents$', views.searchevents, name='searchevents'),	
    url(r'^addevent$', views.addevent, name='addevent'),
    url(r'^addcomment$', views.addcomment, name='addcomment'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.loginpage, name='login'),
    url(r'^logout$', views.logoutpage, name='logout'),	
    url(r'^$', views.home, name='home'),
)

 

worldevents/worldevents/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', include('eventslist.urls')),
    url(r'^eventslist/', include('eventslist.urls')),
)

worldevents/eventslist/models.py
from mongoengine.queryset import QuerySet
from mongoengine import *
from django.conf import settings
import datetime

connect('worldevents')

#####################################################################################

class Comment(EmbeddedDocument):
   content = StringField()
   user = StringField() 
   added_date = DateTimeField(default=datetime.datetime.now)	 

   def __str__(self):
      return self.content	

######################################################################################

class Event(Document):
   
   title = StringField(max_length = 64)
   photo = StringField(max_length = 64)
   location = PointField()
   description = StringField()
   category = StringField()
   added_date = DateTimeField(default=datetime.datetime.now)
   comments = ListField(EmbeddedDocumentField(Comment))	
   user = StringField()

   # Search query
   @queryset_manager
   def search(doc_cls, queryset,title,category,lat,lng,distance,num_events):
      	    if title and category:
		return queryset(Q(location__geo_within_sphere=[(float(lat),float(lng)),float(distance)/6371]) & Q(title__icontains=title) & Q(category=category)).order_by('-added_date')[num_events-15:num_events]
		
	    elif title and not category:
		return queryset(Q(location__geo_within_sphere=[(float(lat),float(lng)),float(distance)/6371]) & Q(title__icontains=title)).order_by('-added_date')[num_events-15:num_events]

	    elif not title and category:
		return queryset(Q(location__geo_within_sphere=[(float(lat),float(lng)),float(distance)/6371]) & Q(category=category)).order_by('-added_date')[num_events-15:num_events]

	    elif not title and not category:
	       return queryset(Q(location__geo_within_sphere=[(float(lat),float(lng)),float(distance)/6371])).order_by('-added_date')[num_events-15:num_events] 
        
      
   def __str__(self):
      return self.title +'-'+str(self.location['coordinates'][0])+str(self.location['coordinates'][1])+'-'+self.description +'-'+self.category

   meta = {'collection':'event'}

##########################################################################################333

class Category(Document):
   name = StringField(max_length = 64, required = True, unique = True)
   
   def __str__(self):
      return self.name
   
   meta = {'collection':'category'}

worldevents/eventslist/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.utils.text import capfirst
from django.forms.widgets import Input
from mongoengine.django.auth import User
from eventslist.models import Category
from django.utils.translation import ugettext_lazy as _


######################################################################################

class RangeInput(Input):
    input_type='range'

#######################################################################################

class SearchForm(forms.Form):
    error_messages = {
        'location_not_selected': _("You must select a location"),  
	'distance_out_of_range': _("Distance must be between 1 and 100"),      
    }    

    title = forms.CharField(label=_("Title"), max_length=30, required=False)
    category = forms.ChoiceField(label=_("Category"), required=False, widget=forms.Select)
    lat = forms.CharField(required=False,widget=forms.HiddenInput)  
    lng = forms.CharField(required=False,widget=forms.HiddenInput) 
    distance = forms.CharField(label=_("Distance"),widget=RangeInput(attrs={'min':'1','max':'100','value':'1'}))    

    # Load categories from database		 
    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        choices = [(unicode(pt), unicode(pt)) for pt in Category.objects.all()]
        self.fields['category'].choices = choices
	self.fields['category'].choices.insert(0,('',_('Select category')))       
    
    # Check location data
    def clean(self):
       cleaned_data = super(SearchForm,self).clean()
       lat = cleaned_data.get("lat")
       lng = cleaned_data.get("lng")
       distance = cleaned_data.get("distance")
       
       if not lat or not lng:
          raise forms.ValidationError(self.error_messages['location_not_selected']) 
       
       if (int(distance)<1) or (int(distance)>100):
	  raise forms.ValidationError(self.error_messages['distance_out_of_range']) 

       return cleaned_data 

#############################################################################################33

class RegistrationForm(forms.Form):
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.RegexField(label=_("Username"), max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text=_("Required. 30 characters or fewer. Letters, digits and "
                      "@/./+/-/_ only."),
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(label=_("Password"),widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    # Check passwords are equal and username don't exist
    def clean(self):
       cleaned_data = super(RegistrationForm,self).clean()
       user_name = cleaned_data.get("username")
       password1 = cleaned_data.get("password1")
       password2 = cleaned_data.get("password2")
       if password1!=password2:
          raise forms.ValidationError(self.error_messages['password_mismatch']) 
       
       if User.objects(username=user_name).count()==1:
	  raise forms.ValidationError(self.error_messages['duplicate_username'])     

       return cleaned_data	

############################################################################################

class CommentForm(forms.Form):
    content = forms.CharField(label="Comment",widget=forms.Textarea)
    
###########################################################################################

class EventForm(forms.Form):
    error_messages = {
        'location_not_selected': _("You must select a location"),       
    }    

    title = forms.CharField(label=_("Title"), max_length=30)
    description = forms.CharField(label=_("Description"),widget=forms.Textarea)
    category = forms.ChoiceField(label=_("Category"),widget=forms.Select)
    photo = forms.ImageField(required=False)	
    lat = forms.CharField(required=False,widget=forms.HiddenInput)  
    lng = forms.CharField(required=False,widget=forms.HiddenInput) 
    
    # Load categories from database
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        choices = [(unicode(pt), unicode(pt)) for pt in Category.objects.all()]
        self.fields['category'].choices = choices
	self.fields['category'].choices.insert(0,('','Select category'))       
    
    # Check if location is selected
    def clean(self):
       cleaned_data = super(EventForm,self).clean()
       lat = cleaned_data.get("lat")
       lng = cleaned_data.get("lng")
       
       if not lat or not lng:
          raise forms.ValidationError(self.error_messages['location_not_selected']) 
       
       return cleaned_data  

worldevents/eventslist/views.py
from eventslist.forms import RegistrationForm,EventForm,SearchForm,CommentForm
from eventslist.models import Category,Event,Comment
from django.http import HttpResponseRedirect
from django.shortcuts import render
from mongoengine.queryset import Q
from mongoengine.django.auth import User
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from mongoengine import *
from django.conf import settings
from time import time
import os
import pymongo
from storages import storage
from django.utils.translation import gettext as _

################################################################################

def home(request,num_events='15'):
   if "event_list" not in request.session: # If there aren't results of a search in session
   	if "search_query" in request.session: # If there is a current search
		event_list=Event.search(request.session['search_query']['title'],request.session['search_query']['category'],request.session['search_query']['lat'],request.session['search_query']['lng'],request.session['search_query']['distance'],int(num_events))
   	else:
		event_list = Event.objects.order_by('-added_date')[int(num_events)-15:int(num_events)]
   else:
	event_list=request.session['event_list'] 
	del request.session['event_list']  

   form = CommentForm()
   return render(request, "eventslist/home.html", {'event_list':event_list,'num_events':num_events,'form':form,})  


##################################################################################

@login_required
def addcomment(request):
   if request.method == 'POST':
	event_id=request.POST['event_id']
	form = CommentForm(request.POST)
	if form.is_valid():
	    content=form.cleaned_data['content']
	    user=request.user.username
	    comment=Comment(content=content,user=user)
            Event.objects(id=event_id).update_one(push__comments=comment)
	    form = CommentForm()
   else:
	form = CommentForm()

   event=Event.objects.get(id=event_id)
   # Return only comments of modified event 
   return render(request, "eventslist/comments.html", {'form':form,'event':event}) 


####################################################################################

def searchevents(request):
   if request.method == 'POST':
	form = SearchForm(request.POST)
        if form.is_valid():
            title=form.cleaned_data['title']
	    category=form.cleaned_data['category'] 
	    lat=form.cleaned_data['lat']
	    lng=form.cleaned_data['lng'] 
	    distance=form.cleaned_data['distance']
	    
	    event_list=Event.search(title,category,lat,lng,distance,15)
	    
	    if event_list: # Put search query and results in session
		request.session["search_query"]={'title':title,'category':category,'lat':lat,'lng':lng,'distance':distance,'num_events':15}
		request.session["event_list"]=list(event_list)
	    else:
		messages.success(request,_('No search results'))
	    
	    return HttpResponseRedirect("/")
   else:
	form = SearchForm()
   return render(request, "eventslist/searchevents.html", {'form':form,})     
  
##############################################################################################

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
	if form.is_valid():
		User.create_user(form.cleaned_data['username'],form.cleaned_data['password1'])  
		messages.success(request, form.cleaned_data['username'] + _(' you have been successfully registered'))
		return HttpResponseRedirect("/")	
    else:
        form = RegistrationForm()
    return render(request, "eventslist/register.html", {
        'form': form,
    })  


##############################################################################################3333333

def loginpage(request):
   if request.method == 'POST':
        form = AuthenticationForm(request.POST)
	username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
	if user is not None:
	   login(request,user)
	   messages.success(request,_('Login Ok ') + user.username)
	   return HttpResponseRedirect("/")
        else:
           messages.success(request,_('Login Fail'))    
   else:
        form = AuthenticationForm()
 
   return render(request,'eventslist/login.html', {
        'form': form,
    })  


#####################################################################################

@login_required
def logoutpage(request):
   logout(request)
   return HttpResponseRedirect("/")

######################################################################################

@login_required
def addevent(request):
    if request.method == 'POST':
	form = EventForm(request.POST, request.FILES)
	
	if form.is_valid():
            title=form.cleaned_data['title']
	    description=form.cleaned_data['description']
            category=form.cleaned_data['category'] 
	    lat=form.cleaned_data['lat']
	    lng=form.cleaned_data['lng']
	    user=request.user.username

	    event = Event(title=title,description=description,category=category,user=user)		

	    if (request.FILES): #If photo is included store in static folder 
		photo_name=request.user.username+"-"+str(int(time()))+".jpeg"
		f=request.FILES["photo"]
		strg=storage()
		getattr(strg,settings.STORAGE+"_write")(photo_name,f)
	    	event.photo=photo_name

            event.location=[float(lat),float(lng)] 
            event.save() 	
            messages.success(request, title + _(' has been created'))
            return HttpResponseRedirect("/")
    else:
	form = EventForm()
      
    return render(request,'eventslist/addevent.html', {
        'form': form,
    })  


###################################################################################

@login_required
def deleteevent(request,event_id):
    if request.method == 'POST':
	event=Event.objects(id=event_id)[0]
	if event.photo is not None: # If event has photo it must be deleted
		strg=storage()
		getattr(strg,settings.STORAGE+"_remove")(event.photo)
		
	event.delete()
	return HttpResponseRedirect("/")
    
    return render(request,'eventslist/deleteevent.html', {
        'id': event_id,
    }) 

###################################################################################

@login_required
def editevent(request,event_id):
    if request.method == 'POST':
	form = EventForm(request.POST, request.FILES)
	if form.is_valid():
	    title=form.cleaned_data['title']
	    description=form.cleaned_data['description']
            category=form.cleaned_data['category'] 
	    photo=Event.objects(id=event_id)[0].photo
	    lat=form.cleaned_data['lat']
	    lng=form.cleaned_data['lng']
	    user=request.user.username

	    event = Event(id=event_id,title=title,description=description,category=category,photo=photo,user=user)		

	    if (request.FILES): # If a photo must be added to event
		strg=storage()
		if photo is not None: # If event had photo it must be deleted
			getattr(strg,settings.STORAGE+"_remove")(photo)	

		photo_name=request.user.username+"-"+str(int(time()))+".jpeg"
		f=request.FILES["photo"]
		getattr(strg,settings.STORAGE+"_write")(photo_name,f)
	    	event.photo=photo_name

            event.location=[float(lat),float(lng)] 
            event.save() 	
            messages.success(request, title + _(' has been updated'))
            return HttpResponseRedirect("/")
    else:
	form = EventForm()
	event=Event.objects(id=event_id)[0]
	form.fields["title"].initial = event.title
	form.fields["description"].initial = event.description
	form.fields["category"].initial = event.category
	form.fields["lat"].initial = event.location['coordinates'][0]
	form.fields["lng"].initial = event.location['coordinates'][1]
	      
    return render(request,'eventslist/editevent.html', {
        'form': form, 'photo': Event.objects(id=event_id)[0].photo, 'id': event_id,
    }) 

worldevents/eventslist/templates/eventslist/addevent.html
{% load i18n %}
<h1>{% trans "Add Event" %}</h1>

	  <form enctype="multipart/form-data" action="{% url 'addevent' %}" method="post">
	      {{ form.as_p }}
	      <img src="#" alt="preview image"/>	
	      <p>{% trans "Select location in the map" %}</p>
              <div id="map_addevent"></div>
	      {% csrf_token %} 
	      <input type="submit" value={% trans "add" %}>
	  </form>
 


 <script type="text/javascript">
	// Draw map
	$( document ).ready(function() {
	  red_icon="http://maps.google.com/mapfiles/ms/icons/red-dot.png"	
          $("#map_addevent").width("300px").height("150px").gmap3({
          map:{
            options:{
              center:[46.578498,2.457275],
              zoom: 3
            },
            events:{
              click: function(map,event){
                $("#id_lat").val(event.latLng.lat());
		$("#id_lng").val(event.latLng.lng());
		drawMarker(event.latLng.lat(),event.latLng.lng())
              }
            }
          }
        });

	//if location already selected
	if (($("#id_lat").val())&&($("#id_lng").val())){
		drawMarker($("#id_lat").val(),$("#id_lng").val())	
	}
	
	//Put selected image in form
	$("input[type='file']").bind("change",function(){
		file=$(this).prop("files")[0]
		img = $("form img[alt='preview image']")
		var reader = new FileReader();
		reader.onload = function(e){
			img.attr('src',e.target.result)
		}
    		reader.readAsDataURL(file);
	});
	
	//Draw marker when user has clicked
	function drawMarker(lat,lng){
		$("#map_addevent").gmap3({
				clear:{
					tag:["selected"]
				},
				marker:{
					latLng:[lat,lng],
					tag:"selected",
					options:{
						draggable:true,
						icon: red_icon
					}
				}
		});
	}


	});

</script>

worldevents/eventslist/templates/eventslist/base.html
{% load staticfiles %}
{% load i18n %}	
<!DOCTYPE html>
<html>
    <head>
        <title>{% trans "WorldEvents" %}</title>
	<meta charset="uft-8">
        {% block stylesheets %}
	{% endblock %}
	{% block javascript %}
	{% endblock %}
    </head>
    <body>
	<header>
		<h1><a href="{% url 'eventslist.views.home' %}">{% trans "WorldEvents" %}</a></h1>
		<nav>
			{% block nav %}
	 		{% endblock %}		
		</nav>
			
	<div id='messages'>
		{% if messages %}
			<ul class="messages">
	    		{% for message in messages %}
	    			<li{% if message.tags %}
					class="{{ message.tags }}"
				   {% endif %}>{{ message }}
				</li>
    			{% endfor %}
			</ul>
		{% endif %}	
	</div>
	</header>
	 {% block content %}
	 {% endblock %}
    
     {% block scripts %}
     {% endblock %}   
    </body>
    
</html>

worldevents/eventslist/templates/eventslist/comments.html
{% load i18n %}			
			{% if user.is_authenticated %}			
				<a href='comment'>{% trans "Add comment" %} </a>			
				<form action="{% url 'addcomment' %}" method="post">
		      			{{ form.as_p }}
		    			{% csrf_token %} 
		      			<input type="submit" value={% trans "add" %}>
				</form>
			{% endif %}
			
			{% if event.comments %}
				<ul>
				{% for comment in event.comments%}
				<li>
					<p>{{comment.user}}</p>
					<p>{{comment.content}}</p>
				</li>
				{% endfor %}
				</ul>
			{% endif %}
			

worldevents/eventslist/templates/eventslist/deleteevent.html
{% load i18n %}	
<h1>{% trans "Delete Event" %}</h1>

	  <form action="{% url 'eventslist.views.deleteevent' %}/{{ id }}" method="post">
	      <p>{% trans "Delete Event,¿are you sure?" %}</p>
              {% csrf_token %} 
	      <input type="submit" value={% trans "Delete" %}>
	      <input type="button" value={% trans "Cancel" %}>	
	  </form>

worldevents/eventslist/templates/eventslist/editevent.html
{% load staticfiles %}
{% load i18n %}	
<h1>{% trans "Edit Event" %}</h1>

	  <form enctype="multipart/form-data" action="{% url 'eventslist.views.editevent' %}/{{ id }}" method="post">
	      {{ form.as_p }}
	      <img src= "{% static "media/" %}{{photo}}" alt="preview image"/>	
	      <p>{% trans "Select location in the map" %}</p>
              <div id="map_addevent"></div>
	      {% csrf_token %} 
	      <input type="submit" value={% trans "Save" %}>
	  </form>
 


 <script type="text/javascript">
	
	$( document ).ready(function() {
	  red_icon="http://maps.google.com/mapfiles/ms/icons/red-dot.png"	
          $("#map_addevent").width("300px").height("150px").gmap3({
          map:{
            options:{
              center:[46.578498,2.457275],
              zoom: 3
            },
            events:{
              click: function(map,event){
                //$("#Location").text("Location: Lat: "+event.latLng.lat()+" Lon: "+event.latLng.lng());
		$("#id_lat").val(event.latLng.lat());
		$("#id_lng").val(event.latLng.lng());
		drawMarker(event.latLng.lat(),event.latLng.lng())
              }
            }
          }
        });

	//if location already selected
	if (($("#id_lat").val())&&($("#id_lng").val())){
		drawMarker($("#id_lat").val(),$("#id_lng").val())	
	}

	//Put selected image in form
	$("input[type='file']").bind("change",function(){
		file=$(this).prop("files")[0]
		img = $("form img[alt='preview image']")
		var reader = new FileReader();
		reader.onload = function(e){
			img.attr('src',e.target.result)
		}
    		reader.readAsDataURL(file);
	});

	//Draw marker when user has clicked
	function drawMarker(lat,lng){
		$("#map_addevent").gmap3({
				clear:{
					tag:["selected"]
				},
				marker:{
					latLng:[lat,lng],
					tag:"selected",
					options:{
						draggable:true,
						icon: red_icon
					}
				}
		});
	}


	});

</script>

worldevents/eventslist/templates/eventslist/eventslist.html
{% load staticfiles %}
{% load i18n %}	
<div id="events_list">	
		<table>
		{% for event in event_list%}
			<tr>
				<td style="display:none;">{{ event.id }}</td>	
				<td style="display:none;">{{ event.location }}</td>				
				<td>{{ event.title }}</td>
				<td>{{ event.category }}</td>
			</tr>
		{% endfor %}
		</table>
		<div id="events_list_control">
			{% with event_list|length as events %} 
			{% if num_events == '15' %}
			<p>&lt;</p>
			{% else %}
			<p><a href="{% url 'eventslist.views.home' %}{{ num_events|add:'-15' }}">&lt;</a></p>	
			{% endif %}
			
			<p>{{ num_events|add:'-14' }}-{{ num_events|add:'-15'|add:events }}</p>
			
			{% if events < 15 %}
			<p>&gt;</p>	
			{% else %}
			<p><a href="{% url 'eventslist.views.home' %}{{ num_events|add:'15' }}">&gt;</a></p>
			{% endif %}
			{% endwith %}
			
		</div>
		</div>
		<div id="back_to_list"><a href="#">{% trans "Back to list" %}</a></div>
		<div id="toggle_map_detail"><a href="#">{% trans "Map/Detail" %}</a></div>
		
		{% for event in event_list%}
		
		<ul class="event_detail" id="{{ event.id }}">
			<li>{{ event.title }}</li>
			<li>{{ event.description }}</li>
			<li>{{ event.category }}</li>
			{% if event.photo %}
				<li><img src="{% static "media/" %}{{ event.photo }}"></li>
			{% endif %}
			{% if user.is_authenticated and user.username == event.user%}
				<a class="form" href="{% url 'eventslist.views.editevent' %}/{{ event.id }}">{% trans "Edit" %}</a>
				<a class="form" href="{% url 'eventslist.views.deleteevent' %}/{{ event.id }}">{% trans "Delete" %}</a>
			{% endif %}
			<div class="comments">
			{% include "eventslist/comments.html" %}
			</div>
			
		</ul>
		{% endfor %}

worldevents/eventslist/templates/eventslist/home.html
{% extends "eventslist/base.html" %}
{% load staticfiles %}
{% load i18n %}	
{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href={% static "css/base.css" %} >
	<link href='http://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,400italic' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Pompiere' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Aladin' rel='stylesheet' type='text/css'>
{% endblock %}
{% block javascript %}
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" ></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src={% static "javascript/gmap3.min.js" %}></script>
	<script type="text/javascript" src={% static "javascript/home.js" %}></script>

{% endblock %}

{% block nav %}
<ul>
{% if user.is_authenticated %}	
	<li><a href="{% url 'eventslist.views.logoutpage' %}">{% trans "Logout" %}</a></li>
	<li><a class="form" href="{% url 'eventslist.views.addevent' %}">{% trans "Add Event" %}</a></li>
			
{% else %}
	<li><a class="form" href="{% url 'eventslist.views.register' %}">{% trans "Registro" %}</a></li>
	<li><a class="form" href="{% url 'eventslist.views.loginpage' %}">{% trans "Login" %}</a></li>

{% endif %}

	<li><a class="form" href="{% url 'eventslist.views.searchevents' %}">{% trans "Search" %}</a></li>
	
</ul>
{% endblock %}	

{% block content %}

	{% if search_parameters %}
	<ul>
{% for key, value in search_parameters %} 
  <li>{{key}} - {{value}}</li>
 {% endfor %}
</ul>
	{% endif %}
	<div id="container">
	{% if event_list %}
		{% include "eventslist/eventslist.html" %}
		<div id="map_detail"></div>
	{% endif %}
	<div>
	<div id="form_container">
	</div>



{% endblock %}
{% block scripts %}
<script type="text/javascript">
	$( document ).ready(init());
</script>
{% endblock %}

worldevents/eventslist/templates/eventslist/login.html
{% load i18n %}	
<div id='messages'>
		{% if messages %}
			<ul class="messages">
	    		{% for message in messages %}
	    			<li{% if message.tags %}class="{{ message.tags }}"
				{% endif %}>{{ message }}</li>
    			{% endfor %}
			</ul>
		{% endif %}	
</div>
{% if form %}
	  <form action="{% url 'login' %}" method="post">
	      {{ form.as_p }}
	      {% csrf_token %} 
	      <input type="submit" value={% trans "login" %}>
	  </form>
{% endif %}

worldevents/eventslist/templates/eventslist/register.html
{% load i18n %}	
  <h1>{% trans "Create an account" %}</h1>

  <form action="{% url 'register' %}" method="post">
      {{ form.as_p }}
      {% csrf_token %} 
      <input type="submit" value={% trans "Create the account" %} >
  </form>

worldevents/eventslist/templates/eventslist/searchevents.html
{% load i18n %}
	
	<h1>{% trans "Search" %}</h1>
	  <form action="{% url 'searchevents' %}" method="post">
	      {{ form.as_p }}
	      <div id="distance">1 km</div>
              <p>{% trans "Select location in the map" %}</p>
              <div id="Location">{% trans "Location" %}:</div>
              <div id="my_map"></div>
	      {% csrf_token %} 
	      <input type="submit" value={% trans "search" %}>
	  </form>

  
<script type="text/javascript">	
	// Draw map
	$( document ).ready(function() {
	  red_icon="http://maps.google.com/mapfiles/ms/icons/red-dot.png"
          $("#my_map").width("300px").height("150px").gmap3({
          map:{
            options:{
              center:[46.578498,2.457275],
              zoom: 10
            },
            events:{
              click: function(map,event){
                $("#Location").text("Location: Lat: "+event.latLng.lat()+" Lon: "+event.latLng.lng());
		$("#id_lat").val(event.latLng.lat());
		$("#id_lng").val(event.latLng.lng());
		drawMarker(event.latLng.lat(),event.latLng.lng())
		drawCircle(event.latLng.lat(),event.latLng.lng(),$("#id_distance").val())
              }
            }
          }
        });
	
	//if location already selected
	if (($("#id_lat").val())&&($("#id_lng").val())){
		drawMarker($("#id_lat").val(),$("#id_lng").val())	
	}
	
	//if distance changes
	$("#id_distance").change(function(){
		$("#distance").text($(this).val()+" km")
		drawCircle($("#id_lat").val(),$("#id_lng").val(),$("#id_distance").val())
	});

	//Draw marker when user has clicked
	function drawMarker(lat,lng){
		$("#my_map").gmap3({
				clear:{
					tag:["selected"]
				},
				marker:{
					latLng:[lat,lng],
					tag:"selected",
					options:{
						draggable:true,
						icon: red_icon
					}
				}
		});
	}

	//Draw distance circle
	function drawCircle(lat,lng,rad){
		$("#my_map").gmap3({
				clear:{
					tag:["circle"]
				},
				circle:{
					tag:"circle",
					options:{
						center: [lat, lng],
      						radius : parseFloat(rad)*1000,
						fillColor : "red",
      						strokeColor : "red"
					}
				}
		});
	}

     });
</script>